persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Esta es la línea clave que lo captura todo
log_type all

connection_messages true
log_timestamp true

#Listener principal mqtt (puerto 1883)
listener 1883
allow_anonymous true