/* 1. Usuarios y Esquema */
CREATE USER 'pecl2_user'@'%' IDENTIFIED BY '1024';
CREATE SCHEMA IF NOT EXISTS UBICOMP;
GRANT ALL PRIVILEGES ON UBICOMP.* TO 'pecl2_user'@'%';
FLUSH PRIVILEGES;
USE UBICOMP;

/* 2. Limpieza (Borrar tablas viejas si existen) */
DROP TABLE IF EXISTS TELEMETRIA;
DROP TABLE IF EXISTS DISPOSITIVO;
DROP TABLE IF EXISTS CALLE;

/* 3. TABLA CALLE (Datos fijos de ubicación) */
CREATE TABLE CALLE (
    STREET_ID VARCHAR(50) PRIMARY KEY,
    ADDRESS VARCHAR(100),
    DISTRICT VARCHAR(50),
    NEIGHBORHOOD VARCHAR(50),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE
);

/* 4. TABLA DISPOSITIVO (Inventario) */
CREATE TABLE DISPOSITIVO (
    SENSOR_ID VARCHAR(50) PRIMARY KEY,
    SENSOR_TYPE VARCHAR(50),
    STREET_ID VARCHAR(50),
    FOREIGN KEY (STREET_ID) REFERENCES CALLE(STREET_ID)
);

/* 5. TABLA TELEMETRIA (Datos históricos) */
CREATE TABLE TELEMETRIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SENSOR_ID VARCHAR(50),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TEMP DOUBLE,
    HUM DOUBLE,
    BRIGHTNESS INT,
    STATUS_MSG VARCHAR(100),
    RAW_JSON JSON, 
    FOREIGN KEY (SENSOR_ID) REFERENCES DISPOSITIVO(SENSOR_ID)
);